
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Apr 02 03:26:08 BRT 2011
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
	/* terminals */
	public static final int GREATERTHAN = 46;
	public static final int LEFTBRACKET = 55;
	public static final int DIVIDE = 43;
	public static final int DOUBLEPOINT = 29;
	public static final int STRING_LITERAL = 57;
	public static final int RIGHTBRACKET = 56;
	public static final int XOR = 26;
	public static final int INV = 17;
	public static final int POINT_VIRGULA = 30;
	public static final int INIT = 16;
	public static final int MINUS = 41;
	public static final int PRE = 23;
	public static final int VIRGULA = 32;
	public static final int NOT = 19;
	public static final int AND = 5;
	public static final int LESSTHAN = 45;
	public static final int IN = 15;
	public static final int OR = 20;
	public static final int IMPLIES = 14;
	public static final int COLLECTION = 35;
	public static final int PIPELINE = 34;
	public static final int PLUS = 50;
	public static final int LESSEQTHAN = 48;
	public static final int MULTIPLY = 42;
	public static final int IF = 13;
	public static final int CONTEXT = 7;
	public static final int EOF = 0;
	public static final int GREATEREQTHAN = 49;
	public static final int TRUE = 27;
	public static final int error = 1;
	public static final int SELF = 2;
	public static final int RIGHTPARENTHESIS = 52;
	public static final int MOD = 44;
	public static final int DERIVE = 9;
	public static final int VOID = 3;
	public static final int RIGHTBRACK = 54;
	public static final int EQ = 40;
	public static final int BODYCONTEXT = 6;
	public static final int DDOUBLEPOINT = 31;
	public static final int ENDPACKAGE = 12;
	public static final int ARROW = 33;
	public static final int ENDIF = 11;
	public static final int ELSE = 10;
	public static final int POST = 22;
	public static final int LEFTBRACK = 53;
	public static final int POINT = 39;
	public static final int PACKAGE = 21;
	public static final int LEFTPARENTHESIS = 51;
	public static final int LET = 18;
	public static final int THEN = 25;
	public static final int DEF = 8;
	public static final int FLOAT_LITERAL = 38;
	public static final int FALSE = 28;
	public static final int ATPRE = 24;
	public static final int NOTEQ = 47;
	public static final int RESULT = 4;
	public static final int INTEGER_LITERAL = 37;
	public static final int IDENTIFIER = 36;
}

