
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Mar 29 00:12:17 BRT 2011
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GREATERTHAN = 35;
  public static final int LEFTBRACKET = 44;
  public static final int DOUBLEPOINT = 48;
  public static final int DIVIDE = 33;
  public static final int STRING_LITERAL = 53;
  public static final int RIGHTBRACKET = 45;
  public static final int XOR = 27;
  public static final int INV = 17;
  public static final int INIT = 16;
  public static final int PRE = 23;
  public static final int MINUS = 31;
  public static final int STATIC = 25;
  public static final int NOT = 19;
  public static final int AND = 5;
  public static final int LESSTHAN = 34;
  public static final int IN = 15;
  public static final int OR = 20;
  public static final int IMPLIES = 14;
  public static final int PLUS = 39;
  public static final int LESSEQTHAN = 37;
  public static final int MULTIPLY = 32;
  public static final int IF = 13;
  public static final int CONTEXT = 7;
  public static final int EOF = 0;
  public static final int GREATEREQTHAN = 38;
  public static final int TRUE = 28;
  public static final int error = 1;
  public static final int SELF = 3;
  public static final int RIGHTPARENTHESIS = 41;
  public static final int MOD = 46;
  public static final int DERIVE = 9;
  public static final int VOID = 50;
  public static final int RIGHTBRACK = 43;
  public static final int EQ = 30;
  public static final int BODYCONTEXT = 6;
  public static final int ENDPACKAGE = 12;
  public static final int ARROW = 49;
  public static final int ENDIF = 11;
  public static final int ELSE = 10;
  public static final int POST = 22;
  public static final int LEFTBRACK = 42;
  public static final int POINT = 47;
  public static final int PACKAGE = 21;
  public static final int LEFTPARENTHESIS = 40;
  public static final int LET = 18;
  public static final int THEN = 26;
  public static final int DEF = 8;
  public static final int FLOAT_LITERAL = 52;
  public static final int FALSE = 29;
  public static final int ATPRE = 24;
  public static final int NOTEQ = 36;
  public static final int RESULT = 4;
  public static final int INTEGER_LITERAL = 51;
  public static final int IDENTIFIER = 2;
}

